baseURL = 'https://hugodemo.trxbroker.at/'
languageCode = 'de-DE'
title = 'Hugo Demo with Tailwind Theme'
theme = 'tailwind'

[markup.goldmark.renderer]
unsafe = true

[[menu.main]]
url = "/impressum"
name = "Impressum"
weight = 1
