baseURL = 'https://hugodemo.trxbroker.at/'
languageCode = 'de-DE'
title = 'Hugo Demo with Tailwind Theme'
theme = 'tailwind'

[markup.goldmark.renderer]
unsafe = true

[[menu.main]]
url = "/about"
name = "About"
weight = 1

[[menu.main]]
url = "/contact"
name = "Contact"
weight = 2

[[menu.main]]
url = "/blog"
name = "Blog"
weight = 3

