baseURL = 'https://hugodemo.trxbroker.at/'
languageCode = 'de-DE'
title = 'Hugo Demo with Tailwind Theme'
theme = 'tailwind'

[markup.goldmark.renderer]
unsafe = true

[[menu.main]]
url = "/page1"
name = "Page 1"
weight = 1

[[menu.main]]
url = "/page2"
name = "Page 2"
weight = 2

[[menu.main]]
url = "/blog"
name = "Blog"
weight = 3

